USE [QL_HOCSINH]
GO

INSERT INTO [dbo].[DIEMDATMON] (MAMH,DiemDat) VALUES ('DD',5.0)
GO

INSERT INTO [dbo].[DIEMDATMON] (MAMH,DiemDat) VALUES ('TO',5.0)
GO

INSERT INTO [dbo].[DIEMDATMON] (MAMH,DiemDat) VALUES ('TD',5.0)
GO

INSERT INTO [dbo].[DIEMDATMON] (MAMH,DiemDat) VALUES ('SI',5.0)
GO

INSERT INTO [dbo].[DIEMDATMON] (MAMH,DiemDat) VALUES ('LY',5.0)
GO

INSERT INTO [dbo].[DIEMDATMON] (MAMH,DiemDat) VALUES ('HO',5.0)
GO

INSERT INTO [dbo].[DIEMDATMON] (MAMH,DiemDat) VALUES ('VA',5.0)
GO

INSERT INTO [dbo].[DIEMDATMON] (MAMH,DiemDat) VALUES ('SU',5.0)
GO

INSERT INTO [dbo].[DIEMDATMON] (MAMH,DiemDat) VALUES ('DI',5.0)
GO

SELECT * FROM DIEMDATMON