USE [QL_HOCSINH]
GO

INSERT INTO [dbo].[KHOI] (MAKHOI) VALUES ('K10')
GO

INSERT INTO [dbo].[KHOI] (MAKHOI) VALUES ('K11')
GO

INSERT INTO [dbo].[KHOI] (MAKHOI) VALUES ('K12')
GO

SELECT * FROM KHOI