USE [QL_HOCSINH]
GO

INSERT INTO [dbo].[LOP] (MALOP,SL,MAKHOI) VALUES ('10A1',40,'K10')
GO

INSERT INTO [dbo].[LOP] (MALOP,SL,MAKHOI) VALUES ('10A2',40,'K10')
GO

INSERT INTO [dbo].[LOP] (MALOP,SL,MAKHOI) VALUES ('10A3',40,'K10')
GO

INSERT INTO [dbo].[LOP] (MALOP,SL,MAKHOI) VALUES ('10A4',40,'K10')
GO

INSERT INTO [dbo].[LOP] (MALOP,SL,MAKHOI) VALUES ('11A1',40,'K11')
GO

INSERT INTO [dbo].[LOP] (MALOP,SL,MAKHOI) VALUES ('11A2',40,'K11')
GO

INSERT INTO [dbo].[LOP] (MALOP,SL,MAKHOI) VALUES ('11A3',40,'K11')
GO

INSERT INTO [dbo].[LOP] (MALOP,SL,MAKHOI) VALUES ('12A1',40,'K12')
GO

INSERT INTO [dbo].[LOP] (MALOP,SL,MAKHOI) VALUES ('12A2',40,'K12')
GO

SELECT * FROM LOP