USE [QL_HOCSINH]
GO

INSERT INTO [dbo].[QUYDINH] (MAQD,GiaTriQD) VALUES ('DIDA',5)
GO

INSERT INTO [dbo].[QUYDINH] (MAQD,GiaTriQD) VALUES ('SLLH',9)
GO

INSERT INTO [dbo].[QUYDINH] (MAQD,GiaTriQD) VALUES ('SLMH',9)
GO

INSERT INTO [dbo].[QUYDINH] (MAQD,GiaTriQD) VALUES ('TMAX',20)
GO

INSERT INTO [dbo].[QUYDINH] (MAQD,GiaTriQD) VALUES ('TMIN',15)
GO

SELECT * FROM QUYDINH
